requires:
- name: "luet"
  category: "system"
  version: ">=0"
- name: "cos-setup"
  category: "system"
  version: ">=0"
- name: "installer"
  category: "utils"
  version: ">=0"
- name: "vanilla"
  category: "kernel"
  version: ">=0"
- category: "system"
  name: "yip"
  version: ">=0"
- name: "cloud-config"
  category: "system"
  version: ">=0"

steps:
- zypper in -y --no-recommends {{.Values.packages}}
# Cleans up cache
- zypper cc
# In opensuse, /bin/sh is a symlink to /etc/alternatives/sh, which points to bash.
# We don't supply etc/alternatives, so handle the symlink by ourselves
- rm -rf /bin/sh && ln -s /usr/bin/bash /bin/sh
- systemctl enable multi-user.target
- systemctl set-default multi-user.target
- systemctl enable cos-setup-reconcile.timer
- systemctl enable cos-setup-fs-after.service
- systemctl enable cos-setup-boot.service
- systemctl enable cos-setup-network.service
- systemctl mask purge-kernels.service

unpack: true
excludes:
- ^/var/cache/luet
- ^/luetbuild
- ^/srv
- ^/root/.bash_history
- ^/run/reboot-needed

# Zypper
- ^/var/lib/zypp
- ^/var/cache/zypp
- ^/usr/share/zypper
- ^/usr/share/zypp
- ^/usr/share/zsh
- ^/usr/share/licenses/zypper
- ^/usr/bin/zypp-.*
- ^/usr/bin/zypper
- ^/usr/lib/zypp$
- ^/usr/lib/zypper
- ^/usr/lib/rpm
- ^/usr/bin/yzpper
- ^/usr/sbin/zypp-.*
- ^/usr/bin/zypp-.*
- ^/usr/bin/susetags2solv
- ^/run/zypp.*
- ^/etc/zypp
- ^/usr/bin/rpm.*
- ^/var/lib/rpm

# Build deps that got thrown-in by zypper
# XXX: To keep until https://github.com/mudler/luet/issues/173 is delivered,
# or we either create another luet repository for runtime deps
- ^/usr/share/bison
- ^/usr/share/automake
- ^/usr/share/autoconf
- ^/usr/share/aclocal
- ^/usr/share/texinfo
- ^/usr/share/libtool

- texinfo.mo
- git.mo
- flex.mo
- ^/usr/libexec/git
- ^/usr/lib64/pkgconfig
- ^/usr/lib64/ldscripts
- ^/usr/lib64/gcc
- ^/usr/bin/git.*
- ^/usr/bin/gcc.*
- ^/usr/bin/flex.*
- ^/usr/bin/autom.*
- ^/usr/bin/autoconf.*
- ^/usr/bin/bison.*
- ^/usr/bin/libtool.*
- ^/usr/x86_64-suse-linux
- ^/usr/lib64/rpm-plugins
# Yast
- ^/var/lib/YaST2

# Perl
- ^/usr/bin/perl.*
- ^/usr/lib/perl.*

# Wget - we are only shipping curl
- ^/etc/wgetrc
- ^/usr/share/licenses/wget/COPYING
- ^/usr/bin/wget

# General
- ^/usr/include
#- ^/usr/local
- ^/usr/local/bin
- ^/usr/local/go
- ^/usr/local/include
- ^/usr/local/lib.*
- ^/usr/local/man
- ^/usr/local/sbin
- ^/usr/local/share
- ^/usr/local/src

# Some golang package leftovers
- ^/root/.cache
