# Default cOS OEM configuration file - 
stages:
   fs.after:
     - name: "Setup Luet config file"
       directories: 
       - path: "/etc/luet"
         permissions: 0600
         owner: 0
         group: 0
       files:
       - path: /etc/luet/luet.yaml
         content: |
                  logging:
                    color: false
                    enable_emoji: false
                  general:
                     debug: false
                     spinner_charset: 9
                  system:
                    rootfs: /tmp/upgrade
                    database_engine: "memory"
                  repositories:
                  - name: "cos"
                    description: "cOS official"
                    type: "docker"
                    enable: true
                    cached: true
                    priority: 1
                    urls:
                    - "raccos/releases-amd64"
         permissions: 0600
         owner: 0
         group: 0
       - path: /etc/cos-upgrade-image
         content: "system/cos"
         permissions: 0600
         owner: 0
         group: 0
