requires:
- name: "uroot"
  category: "system"
  version: ">=0"
- category: "kernel"
  name: "default"
  version: ">=0"
env:
- PATH=$PATH:/usr/local/go/bin
- GOPATH=/luetbuild/go
- GO111MODULE=off
- CGO_ENABLED=0

prelude:
- mkdir /boot || true
- rm -rf $GOPATH/src/github.com/u-root/u-root/cmds/core/init
- cp -rf init $GOPATH/src/github.com/u-root/u-root/cmds/core/init

steps:

# grab deps library for udev probe init functionalities
- go get github.com/pilebones/go-udev

- mkdir modules
- find /lib/modules/**/kernel/fs  -exec cp {} --parents ./modules \;
- find /lib/modules/**/kernel/lib  -exec cp {} --parents ./modules \;
- find /lib/modules/**/kernel/crypto  -exec cp {} --parents ./modules \;
- find /lib/modules/**/kernel/crypto  -exec cp {} --parents ./modules \;
- find /lib/modules/**/kernel/drivers/usb  -exec cp {} --parents ./modules \;
- find /lib/modules/**/kernel/drivers/hid  -exec cp {} --parents ./modules \;
- find /lib/modules/**/kernel/drivers/input  -exec cp {} --parents ./modules \;
- find /lib/modules/**/kernel/drivers/block  -exec cp {} --parents ./modules \;
- find /lib/modules/**/kernel/drivers/ata -exec cp {} --parents ./modules \;
- find /lib/modules/**/kernel/drivers/md -exec cp {} --parents ./modules \;
- find /lib/modules/**/kernel/drivers/virtio  -exec cp --parents {} ./modules \;
- find /lib/modules/**/kernel/drivers/cdrom  -exec cp --parents {} ./modules \;
- find /lib/modules/**/kernel/drivers/scsi  -exec cp --parents {} ./modules \;
- find /lib/modules/**/kernel/drivers/md  -exec cp {} --parents ./modules \;

# Ethernet + address family: af_packet
- find /lib/modules/**/kernel/drivers/net/ethernet  -exec cp --parents {} ./modules \;
- find /lib/modules/**/kernel/net/packet  -exec cp --parents {} ./modules \;
- cp -rf /lib/modules/**/modules.* ./modules/lib/modules/**/

- |
   u-root \
   -files "/luetbuild/loader.sh:/loader" \
   -files "/luetbuild/modules/lib/modules:/lib/modules" \
   -files "/sbin/blkid" \
   -files "/usr/bin/mount" \
   -files "/usr/sbin/modprobe" \
   -files "/usr/sbin/depmod" \
   -files "/usr/sbin/losetup" \
   -files "/usr/bin/setsid" \
   -files "/sbin/switch_root" \
   -files "/bin/mkdir" \
   -files "/bin/sh" \
   -format=cpio -build=bb -defaultsh="" -o initramfs.cpio github.com/u-root/u-root/cmds/core/{ip,ls,dhclient,init,cat,echo,chroot,sleep}

- |
   xz --check=crc32 -9 --lzma2=dict=1MiB \
      --stdout initramfs.cpio \
      | dd conv=sync bs=512 \
      of=/boot/initramfs

excludes:
- ^/luetbuild
- ^/root
